### PR TITLE
Update navigation.css

### PR DESCRIPTION
**Pull request by ariyoaresa**
# 7

# This PR makes the nav bar mobile responsive

### CODE REVIEW

**Comment by CodeTorso** [comment]
Good temporary fix.

In future other contributors may add hamburger menu but till that time. This fix will do the job.

@AdarshRawat1 you can merge this PR but merge it after PR #4

**Comment by ariyoaresa** [comment]
> Good temporary fix.
> 
> In future other contributors may add hamburger menu but till that time. This fix will do the job.
> 
> @AdarshRawat1 you can merge this PR but merge it after PR #4
>
> please add a "hacktoberfest-approved" label after the pr

**Comment by ariyoaresa** [comment]
Please add an "hacktoberfest-approved" label after the PR

**Comment by AdarshRawat1** [comment]
@ariyoaresa resolve the merge conflicts and then we can add the hacktoberfest and hactoberfest-accepted tag to your PR

**Comment by CodeTorso** [comment]
Can you make me a maintainer to this Repo. I am done with my HacktoberFest contribution. Now let me help other?

**Pull request closed without merging**
