### PR TITLE
UI Changes - Hacketoberfest

### PR DESCRIPTION
**Pull request by Nitish36**
# UI Changes

# Description

I have made the required changes to the UI and tried to make it more responsive as per what I had told
Please merge this with the original code

Thank You :)

### CODE REVIEW

**Comment by CodeTorso** [comment]
@AdarshRawat1 Can I get maintainer permissions. To run the code locally and do some other things with code for this repo. 

Sorry @Nitish36 I was busy working on OpenCodeEra 1 responsiveness.

**Comment by Nitish36** [comment]
Okay

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 Can I get maintainer permissions. To run the code locally and do some other things with code for this repo.


Pardon the delay @CodeTorso , I am having my midterm exams.

**Comment by AdarshRawat1** [comment]
@Nitish36 
I noticed that the  PR includes a significant number of line changes. 
It appears as though some files may have been deleted and then pasted again, which could explain the high number of line changes. Is this the case?

p.s. - If you pasted those files (after deletion) then about this approach as it makes it difficult for maintainers ( @CodeTorso ) to track the changes that you have made to the code base.

**Comment by Nitish36** [comment]
@AdarshRawat1 I have just modified the codes with the latest one which I felt was good enough may be those might have got counted as deleted but I haven't deleted any files. They are like as it is

**Pull request closed without merging**
